# This is a Horizontal Pod Autoscaler (HPA) configuration  to scale demo-app pods between 2 and 6 replicas based on CPU utilization. 
# It monitors the CPU usage of the pods in the demo-app deployment 
#and automatically adjusts the number of replicas to maintain an average CPU utilization of 70%.

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-app-hpa
  namespace: demo-app
  labels:
    app: demo-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-app
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Target CPU utilization percentage for scaling 