# Isolates demo-app resources from other workloads in the cluster by creating a dedicated namespace.
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
  labels:
    name: demo-app   # k8s label to identify the namespace
    istio-injection: enabled  # Enables Istio sidecar injection for pods in this namespace  