#!/bin/bash

# Setup script for cicd-worker node. Generated by Bob AI

echo "Setting up worker node..."

# Update system
sudo apt update && sudo apt upgrade -y

# Install Docker
sudo apt install docker.io git -y

# Add ubuntu to docker group
sudo usermod -aG docker ubuntu

# Setup hostname
sudo hostnamectl set-hostname cicd-worker

# Setup aliases
echo "alias k='microk8s kubectl'" >> ~/.bashrc
source ~/.bashrc

echo "Worker node setup complete!"

echo "Next steps:"
echo " 1. exit and reconnect"
echo " 2. On master run: microk8s add-node"
echo " 3. Run join command with --worker flag"
