#!/bin/bash

# Setup script for cicd-master node. Generated by Bob AI

echo "Setting up master node..."

# Update system
sudo apt update && sudo apt upgrade -y

# Install AWS CLI + Docker
sudo apt install awscli docker.io git -y

# Add ubuntu to docker group
sudo usermod -aG docker ubuntu

# Setup kubeconfig
mkdir -p ~/.kube
microk8s config > ~/.kube/config

# Setup aliases
echo "alias k='microk8s kubectl'" >> ~/.bashrc
echo "alias kubectl='microk8s kubectl'" >> ~/.bashrc
source ~/.bashrc

# Enable MicroK8s addons
microk8s enable dns storage helm3 metrics-server

# Setup Istio PATH
echo "export PATH=~/istio-1.26.0/bin:$PATH" >> ~/.bashrc
source ~/.bashrc

echo "Master node setup complete!"

echo "Next steps:"
echo " 1. aws configure"
echo " 2. git clone your repo"
echo " 3. Install Istio: istioctl install --set profile=minimal -y"
echo " 4. Install Prometheus: microk8s helm3 install prometheus..."
